name: Deploy Web

on:
  push:
    branches:
      - main
    paths:
      - client/**

jobs:
  deploy:
    name: Lint, Test & Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: client/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: shopping-list-client
          heroku_email: sasantazayoni@gmail.com
          appdir: client
