name: Deploy API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - server/**

jobs:
  deploy:
    name: Lint & Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: server/package-lock.json
      - run: npm ci
      - run: npm run lint
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cd $GITHUB_WORKSPACE
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/shopping-list-server.git
          git push heroku $(git subtree split --prefix server HEAD):main --force
